"""Emit the browser engine's configuration from the frozen YAMLs.

The page cannot read YAML, and hand-copying the frozen parameters into
JavaScript is exactly how two implementations drift apart. This generates them,
so `web/worlds.js` is never edited by hand and always carries the config hash it
came from.

    .venv/bin/python scripts/build_web.py
"""

from __future__ import annotations

import json
from pathlib import Path

from foundersim.config import RunConfig

WORLDS = {
    "smallcap": ("configs/smallcap.yaml", "Small-cap", "Grounded on 2025-26 round sizes and "
                 "lower-middle-market exit multiples. Companies top out near $50M of revenue."),
    "venture": ("configs/frozen.yaml", "Venture ladder", "The headline configuration: rounds up "
                "to $150M and exits into the hundreds of millions."),
}


def main() -> None:
    out = {}
    for key, (path, label, blurb) in WORLDS.items():
        cfg = RunConfig.from_yaml(path)
        out[key] = {
            "label": label,
            "blurb": blurb,
            "hash": cfg.hash(),
            "source": path,
            "config": cfg.to_dict(),
        }

    body = json.dumps(out, indent=1, sort_keys=True)
    text = (
        "/* Generated by scripts/build_web.py — do not edit.\n"
        " *\n"
        " * The frozen configurations, as the browser engine needs them. Regenerate\n"
        " * after any recalibration; the hashes below identify which run each came\n"
        " * from, and web/sim.html displays them so a reader can trace any number\n"
        " * on the page back to the config that produced it.\n"
        " */\n\n"
        f"const WORLDS = {body};\n\n"
        'if (typeof module !== "undefined" && module.exports) module.exports = WORLDS;\n'
    )
    Path("web/worlds.js").write_text(text)
    for key, world in out.items():
        print(f"  {key:9s} {world['hash']}  {world['source']}")
    print(f"wrote web/worlds.js ({len(text)} bytes)")


if __name__ == "__main__":
    main()
